# Hand-written descriptions (from visual review of the contact sheets).
D={
# ---- branding
'icons/icon':('logo','App icon: navy heater shield, gold embroidered blackletter "C" under a crown, gold rope rim (webp copy).','Monogram stamp / end-card seal / wax-seal style transition; 512px -> fine up to ~700px on screen.'),
'icons/icon_source':('logo','Same app icon, original PNG stored raw in the pck (lossless).','Prefer this over icons/icon (identical design, true source).'),
'table_tapestry/banner_side_left':('banner','Tall navy swallow-tail hanging with gold rampant lion, gold fringe, hung from a brass rod (menu side banner).','Hall dressing for the oath feast (0-13s) or frame the end title; 642px tall -> keep <= ~900px on screen.'),
'table_tapestry/banner_side_right':('banner','Tall red swallow-tail hanging with gold rampant lion and vine, gold fringe (menu side banner).','Pair with banner_side_left to flank the title card; red/blue = rival realms.'),
'table_tapestry/logo_banner':('logo','Navy velvet valance on a wooden rod: gold blackletter "Chronica", crown, fleurs-de-lis, gold tassels and fringe (smaller version).','Secondary title / lower-third; use logo_title for the hero shot.'),
'table_tapestry/logo_title':('logo','HERO TITLE: navy velvet valance, gold embroidered blackletter "Chronica", crown, fleurs-de-lis, gold bullion fringe, tassels, turned wooden rod with brass finials. Best-resolution branding asset.','Final title reveal (~56-66s). 1741px wide = 68% of a 2560 frame at 1:1; animate drop-in / fringe sway; do not upscale >1.3x.'),
'table_tapestry/ribbon':('ribbon','Blank navy fabric ribbon scroll with gold edging and folded ends.','Caption ribbon for subtitles or the "one banner, one village, one blank page" (50.8-54.9s) words; 378x56 so scale <=2x.'),
'ui/game_over_defeat':('banner','Torn dark-brown embroidered banner: broken spear, tattered red pennant, frayed holes, fleur-de-lis end caps (game-over defeat).','Hundred years war / "ended nothing" beat (28-32s) as a cartouche over war_bg, or broken-oath motif.'),
'ui/game_over_victory':('banner','Black velvet banner, gold crown flanked by gold laurel branches, fleur-de-lis end caps (game-over victory).','"One crown" (0-8s) or "made whole again" (46-50s) cartouche; 1520x400 is strong enough for ~60% frame width.'),
'ui/logo_chronica':('logo','Gold-thread "CHRONICA" in roman capitals with a hexagonal crown medallion, transparent background.','Clean end-card wordmark / corner bug; 1800x440.'),
'ui/menu_veil':('overlay','Dark brown linen curtain (1800x2400), gold vine-scroll embroidered border on the left edge; right ~40% fades to transparent.','Curtain wipe between beats, dark edge vignette for "world grew dark at its edges" (38-44s), or title-card side panel.'),
'ui/topbar':('panel','Black linen plate with gold Celtic-knot corners and gold rope frame (512x160).','Caption / subtitle plate.'),
'ui_embroidery_v2/vignette_blue':('vignette','Linen strip with a navy rampant lion between embroidered flowers, navy/gold border (720x208).','Chapter interstitial / realm emblem; blue realm.'),
'ui_embroidery_v2/vignette_red':('vignette','Linen strip with a red rampant lion between flowers, navy border (720x198).','Red realm counterpart of vignette_blue - rival lords.'),
'ui_linen/millefleurs':('texture','Small cream linen tile with scattered embroidered flowers (red/blue/white) on a gold vine (240x104), tileable.','Mille-fleurs background tile for the "blank page" / end card, or tapestry border fill.'),
# ---- heraldry
'ui/crest_builders':('crest','Faction crest (512): orange/gold shield, dark hexagon with hammer, gold rim. Matches the gold-tunic lord in p1_oath.','Lord/faction identification; "every lord ... saw his own head beneath the crown" (18.7-26.6s), "every ruler" (46-50s).'),
'ui/crest_legion':('crest','Faction crest (512): red shield, gold eagle over a sword. Matches the red-tunic lord in p1_oath.','As above (Legion faction).'),
'ui/crest_merchants':('crest','Faction crest (512): blue shield, gold scales and coin. Matches the blue-tunic lord in p1_oath.','As above (Merchants faction).'),
'ui/crest_nomads':('crest','Faction crest (512): green shield, black raven over a white horse head. Matches the green-tunic lord in p1_oath.','As above (Nomads faction).'),
'table_heraldry/shield_blue':('shield','Heater shield, navy with gold fleur-de-lis, bronze rim (202x256).','Realm shield (blue). Heraldic line-up, map markers, transitions.'),
'table_heraldry/shield_gold':('shield','Heater shield, gold with dark sunburst, bronze rim (221x256).','Realm shield (gold).'),
'table_heraldry/shield_green':('shield','Heater shield, green with cream saltire, bronze rim (212x256).','Realm shield (green).'),
'table_heraldry/shield_red':('shield','Heater shield, red with cream cross, bronze rim (202x256).','Realm shield (red).'),
'table_heraldry/realm_banner_blue':('realm_banner','Tiny hanging banner (80x104) navy, gold fringe, rod.','"One banner" (50.8s) planted on the map; small - keep <= ~250px on screen.'),
'table_heraldry/realm_banner_gold':('realm_banner','Tiny hanging banner, gold.','As realm_banner_blue.'),
'table_heraldry/realm_banner_green':('realm_banner','Tiny hanging banner, green.','As realm_banner_blue.'),
'table_heraldry/realm_banner_neutral':('realm_banner','Tiny hanging banner, undyed linen/grey.','Neutral / unclaimed banner - "one blank page" pairing.'),
'table_heraldry/realm_banner_red':('realm_banner','Tiny hanging banner, red.','As realm_banner_blue.'),
'ui_linen/lion_blue':('heraldic_charge','Small flat-stitched lion passant, navy thread (96x76), older linen UI set.','Map marker / tiny charge; low res.'),
'ui_linen/lion_red':('heraldic_charge','Small flat-stitched lion passant, red thread (96x76).','As lion_blue.'),
'ui_linen/shield_blue':('shield','Small linen-set shield, navy satin stitch with gold fleur-de-lis (72x84).','Tiny marker only.'),
'ui_linen/shield_red':('shield','Small linen-set shield, red with gold fleur-de-lis (72x84).','Tiny marker only.'),
'ui_linen/banner_edge':('ui_9slice','Tiny banner edge 9-slice piece (40x56).','Negligible.'),
'ui_linen/banner_fill':('ui_9slice','Tiny white banner fill piece (40x56).','Negligible.'),
# ---- ornaments
'table_backgrounds/candle_left':('prop','Lit cream wax candle in a brass candlestick (200x720), transparent.','Foreground dressing for the oath feast / lying-in-state (0-18s); flicker the flame with a warp + glow.'),
'table_backgrounds/candle_right':('prop','Second lit candle in brass candlestick (212x720).','Pair with candle_left.'),
'table_backgrounds/lion_statue_left':('prop','Carved walnut seated lion holding a navy shield, on a plinth (361x520).','Frame sentinels for title / end card.'),
'table_backgrounds/lion_statue_right':('prop','Carved walnut seated lion holding a red fleur-de-lis shield (364x520).','Pair with lion_statue_left.'),
'table_backgrounds/table_edge_bottom':('prop','Walnut shelf with carved acanthus apron, brass corners, lit candle, two leather books, sealed rolled scroll, gold coins (1336x320).','Chronicler\'s desk foreground for the closing question (56-62s) / "blank page" beat.'),
'table_carved/apron':('ornament','Carved walnut acanthus apron with brass boss (580x120).','Top/bottom frame ornament.'),
'table_carved/bracket_left':('ornament','Carved acanthus scroll bracket (210x70).','Frame corner flourish.'),
'table_carved/bracket_right':('ornament','Carved acanthus scroll bracket, mirrored (202x66).','Frame corner flourish.'),
'table_carved/pillar':('ornament','Turned walnut column with brass collars (44x222).','Frame pillar (thin, low res).'),
'table_carved/pillar_base':('ornament','Pillar base 9-slice piece (44x74).','Frame pillar part.'),
'table_carved/pillar_cap':('ornament','Brass pillar capital (44x84).','Frame pillar part.'),
'table_carved/pillar_collar':('ornament','Brass pillar collar (44x20).','Frame pillar part.'),
'table_carved/pillar_shaft':('ornament','Walnut pillar shaft tile (44x64).','Frame pillar part (tile vertically).'),
'table_parchment/plaque':('ornament','Parchment name plaque in a walnut frame with brass corners (232x52).','Caption plate.'),
'table_parchment/rule_line':('ornament','Tiny walnut rule line (49x12).','Negligible.'),
'table_parchment/rule_orn':('ornament','Tiny carved fleur rule ornament (47x24).','Small divider flourish.'),
'table_wood/bar_bottom':('ornament','Carved walnut bar with brass corners and acanthus (901x134).','Letterbox bar / caption shelf.'),
'table_wood/bar_top':('ornament','Walnut top bar with acanthus ends (703x80).','Letterbox bar.'),
'table_wood/column_rail':('panel','Walnut panel with brass corners (344x878).','Side panel.'),
'table_wood/divider_v':('ornament','Thin vertical walnut divider (21x256).','Negligible.'),
'table_wood/frame_map':('frame','Walnut picture frame, 9-slice (340x335).','Frame for the map / tapestry panel (9-slice scale).'),
'ui/separator':('ornament','Gold twisted-cord line (512x16).','Subtitle underline, title rule.'),
'ui_linen/frame':('frame','Rope-bordered linen frame (72x72), 9-slice.','Small frame.'),
'ui_linen/groove':('ornament','Tiny groove stitch tile (24x16).','Negligible.'),
'ui_linen/orn_left':('ornament','Embroidered flourish: navy/gold fleur-de-lis with gold cord vine and little flowers (150x72).','Title flourish (flank text), 2x max.'),
'ui_linen/orn_right':('ornament','Mirrored flourish of orn_left (150x72).','Title flourish.'),
'ui_linen/plaque':('ornament','Tiny linen plaque (40x40).','Negligible.'),
'ui_linen/satin_or':('texture','Gold satin-stitch swatch tile (24x16).','Gold thread colour/texture reference; tileable fill.'),
'ui_linen/sep_h':('ornament','Tiny stitch separator (20x8).','Negligible.'),
'ui_linen/sep_v':('ornament','Tiny stitch separator (8x20).','Negligible.'),
# ---- clouds
'table_clouds/cloud_corner_in':('cloud','Quilted cream cloud corner (inner), swirls outlined by brown running stitch (256x240) - the in-game fog-of-war border kit.','Fog closing in from frame edges: "the world grew dark at its edges" (38-44.5s); transition wipes.'),
'table_clouds/cloud_corner_out':('cloud','Quilted cloud corner (outer) (256x253).','As cloud_corner_in.'),
'table_clouds/cloud_edge_1':('cloud','Horizontal quilted cloud edge strip (512x121), bottom edge scalloped swirls.','Tile along frame edges for a fog vignette; reveal/conceal map.'),
'table_clouds/cloud_edge_2':('cloud','Cloud edge strip variant (512x150).','As cloud_edge_1.'),
'table_clouds/cloud_edge_3':('cloud','Cloud edge strip variant (512x126).','As cloud_edge_1.'),
'table_clouds/cloud_fill':('cloud','Tileable quilted swirl-cloud fill (512x512, has mips).','Fill the unknown world / full-frame fog bed; parallax layer.'),
'table_clouds/cloud_mask_soft':('mask','Soft radial white gradient (256x256).','Soft alpha mask for cloud blending / glows.'),
'table_clouds/puff_atlas':('cloud','Atlas of 8 small quilted cloud puffs (1024x512, 4x2).','Drifting sky puffs over tapestry panels.'),
}
for i in range(1,9):
    D[f'table_clouds/cloud_puff_{i}']=('cloud',f'Single quilted cream cloud puff #{i}, swirl motifs with brown running-stitch outline, transparent.','Drifting clouds / parallax over map and panels; fog transitions (38-44.5s). 256px wide -> keep <=~600px on screen.')
UNIT={'archer':'archer in orange tunic with white hood, longbow (strike: draws the bow)',
'catapult':'wooden catapult on 4 spoked wheels with linen pennant (strike: arm fires stone)',
'engineer':'bearded engineer with hammer and scroll (strike: hammer blow)',
'goblin':'green goblin with spear and rag kilt (strike: spear thrust lunge)',
'horse_archer':'mounted archer on a grey horse (strike: galloping, drawing bow)',
'knight':'mounted knight with great helm, lance with pennant, shield, caparisoned brown horse (strike: galloping lance couched)',
'legionary':'Roman-style legionary with crested helmet, lorica, rectangular scutum (strike: gladius thrust)',
'man_at_arms':'man-at-arms in kettle hat and mail with sword and heater shield (strike: sword raised overhead)',
'mercenary':'bearded mercenary in pink/red doublet with axe (strike: axe raised overhead)',
'scout':'cloaked scout with hood (idle: shading eyes; strike: dagger thrust)',
'spearman':'spearman in nasal helm, padded tunic, spear and heater shield (strike: spear levelled)'}
ICON_UNIT={'archer':'green-hooded archer with longbow','catapult':'wooden catapult with sling','engineer':'bearded engineer with sledgehammer','goblin':'grinning goblin in hood','horse_archer':'steppe horse-archer and horse','knight':'knight in great helm with blue lion tabard and fleur banner','legionary':'legionary in crested helmet with scutum and gladius','man_at_arms':'man-at-arms with sword and shield','mercenary':'bearded axe mercenary','scout':'hooded scout shading eyes','spearman':'spearman in nasal helm, blue gambeson'}
