import {chromium} from '/opt/node22/lib/node_modules/playwright/index.mjs';
import fs from 'fs';
const G='/tmp/claude-0/-home-user-chronica-ipad/ae358f8e-1e70-5169-a8ed-87e6e6e15cfd/scratchpad/aaa/game';
const OUT=G+'/boot3';
const t0=Date.now();
const log=(...a)=>{const s=`[${((Date.now()-t0)/1000).toFixed(1)}s] `+a.join(' ');console.log(s);fs.appendFileSync(OUT+'/boot.log',s+'\n');};
let html=fs.readFileSync('/home/user/chronica-ipad/index.html','utf8');
const snip=fs.readFileSync(G+'/intro_overlay_snippet.html','utf8');
const anchor='<div id="notice"></div>\n</div>\n';
if(!html.includes(anchor)) throw new Error('anchor not found');
const cut=snip.indexOf('<!-- ===== Part B');
html=html.replace(anchor,anchor+snip.slice(0,cut)+'\n');
const bootEnd='}());\n</script>\n</body>';
if(!html.includes(bootEnd)) throw new Error('boot anchor not found');
html=html.replace(bootEnd,'}());\n</script>\n'+snip.slice(cut)+'\n</body>');
fs.writeFileSync(OUT+'/index_with_intro.html',html);
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',headless:true,
  args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--autoplay-policy=no-user-gesture-required']});
const ctx=await b.newContext({viewport:{width:960,height:540},deviceScaleFactor:1});
const p=await ctx.newPage();
p.on('console',m=>log('console.'+m.type(),m.text().slice(0,200)));
p.on('pageerror',e=>log('pageerror',String(e).slice(0,300)));
await p.route('http://127.0.0.1:8765/index.html',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:html}));
await p.route('**/intro/intro_1080.webm',r=>r.fulfill({status:200,contentType:'video/webm',body:fs.readFileSync(G+'/www/intro_test.webm')}));
await p.route('**/intro/intro_1080.mp4',r=>r.fulfill({status:404,body:''}));
await p.route('**/intro/poster.jpg',r=>r.fulfill({status:404,body:''}));
await p.addInitScript(()=>{window.__ev=[];const T=()=>Math.round(performance.now());
  new PerformanceObserver(l=>{for(const e of l.getEntries()){ if(/index\.(pck|wasm)$/.test(e.name)) window.__ev.push(['res_end '+e.name.split('/').pop(),Math.round(e.responseEnd)]);}}).observe({type:'resource',buffered:true});
  const ol=console.log; console.log=function(...a){ if(String(a[0]).startsWith('Godot Engine')) window.__ev.push(['godot_callMain',T()]); return ol.apply(this,a);};
  document.addEventListener('DOMContentLoaded',()=>{const v=document.getElementById('introVideo');
    ['play','playing','ended','error'].forEach(e=>v.addEventListener(e,()=>window.__ev.push([e,T()])));
    const st=document.getElementById('status');
    new MutationObserver(()=>window.__ev.push(['status_style',T()])).observe(st,{attributes:true});
    new MutationObserver(ms=>{for(const m of ms)for(const n of m.removedNodes)window.__ev.push(['removed '+n.id,T()]);}).observe(document.body,{childList:true});
    const intro=document.getElementById('intro');
    new MutationObserver(()=>window.__ev.push(['intro_attr '+intro.className+' op='+intro.style.opacity,T()])).observe(intro,{attributes:true});
  });});
await p.goto('http://127.0.0.1:8765/index.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(4000);
await p.screenshot({path:OUT+'/a_intro_playing.png'}); log('shot a');
for(let i=0;i<400;i++){ const gone=await p.evaluate(()=>!document.getElementById('intro')); if(gone){log('intro removed');break;} await p.waitForTimeout(500);} 
const info=await p.evaluate(()=>({ev:window.__ev,st:window.__chronicaIntro}));
log('events',JSON.stringify(info));
const g=await p.evaluate(()=>{ return 'no direct handle'; });
await p.screenshot({path:OUT+'/b_after_handoff.png'}); log('shot b');
await b.close(); log('done');
