"""Shot data for CHRONICA storyboard v1 (merged final). Imported by gen_storyboard_v1.py.
Technique codes: R25-F relight25d frontal relight (cached maps); R25-S relight25d stitch-on / unpick;
R25-L relight25d frontal slip lift; EV-DM Eevee render of a displaced mesh built from R25 maps;
COMP numpy/cv2 compositor (every frame passes through it); GP game demo-mode plate / native capture."""

SHOTS = [
dict(id="S01", name="The first thread", act="I Oath", start=0, end=90,
 anchor="silence f0-3; 'There' f4/f5; 'world' f39",
 summary="Needle draws the gold chronicle thread up through linen in macro; pull-back between the threads",
 audio_event="f0-3 digital silence. f4 D-drone fade-in with 'There' (strongest attack of the file, f5); 'time' f19; 'world' f39 (stressed); 'only' f63; 'one' f76 on a +9 dB drone swell.",
 visual_action="f0-3 black #07070A. f4: one raking candle (1900 K, elev 8 deg, from upper left) blooms on bare linen weave in macro: slubs, fuzz, the faint brown underdrawing of the upper border. f5 'There': the point of a steel needle breaks up through the weave from behind, its eye dragging the two-ply silver-gilt chronicle thread; f5-38 the thread slides up through the hole, a modest glint riding its twist, linen fibres springing back round the hole. f39 'world': the thread draws taut and lies down along the underdrawn line, a crimson silk tie-down pinches it (the first couching stitch of the chronicle) and the needle leaves frame top right. f40-90: the pull-back starts; we rise off the weave, between the couched pair and out over the upper border (paired lion beasts in diagonal-bar compartments, the first nail holes and foxing); on 'one' f76 the hillock bands of the realm enter below. The light warms toward 3000 K and climbs toward 22 deg.",
 camera="f4-39 locked macro, ~96 mm field (27 px/mm), f/8, cloth tilted 15 deg so a ~5 mm focus band crosses the thread; focus racks needle tip (f5) to thread (f30); 1 px/frame drift. f40-110 exponential pull-back 96 -> 776 mm field (8x), cubic ease-in from f40, landing at F0 (3.3 px/mm) by f110 in S02. Frame centre < 8 px/frame; frame-edge texture peaks ~50 px/frame and is always under 180-deg motion blur (real Eevee blur to f75, radial blur in COMP after). DOF opens as the field widens.",
 technique="EV-DM macro rig E0: Blender 4.0.2 Eevee 1920x1080, 16 TAA, on ones f4-75 (72 renders; f0-3 are black). 120x80 mm patch displaced from R25's linen generator (low-pass height as geometry at 0.25 mm spacing, high-pass as normal map), border underdrawing and lion albedo from the R25 border kit, thread as a 2-ply twisted curve sliding along its path, steel needle mesh, real DOF and camera motion blur. f66-76 registered crossfade to R25-F (same maps, same light vector), which carries the rest of the pull at 13-20 px/mm map density. COMP adds fuzz halo, grain and the act grade; Lanczos upscale 1080 -> 1440.",
 material_behavior="Linen tabby with slubs and per-thread tone, back-lit fuzz halo. Silver-gilt pair: thin anisotropic glint (level L2, capped at gold_hi #F8D57C) interrupted at the crimson tie-down. Steel needle: one hard highlight for 1-3 frames. Lion beasts matte wool. Ageing at 20-30 % of survey density, concentrated on the top hem (nail holes with rust halo).",
 transition_out="Continuous: the pull-back carries into S02.",
 emotional_purpose="Hush and material truth before any story: a real, old, handmade object, and the chronicle begins with a verb, a needle drawing one thread.",
 est_render_cost="Eevee E0 72 renders @1080p 16 TAA (~65 s each, ~1M-vert displaced patch) = ~78 min single process; R25-F 25 frames x ~5 s = ~2 CPU-min; COMP 91 x 0.4 s.",
 eevee=dict(block="E0", r1080=72, r1440=0)),

dict(id="S02", name="One realm", act="I Oath", start=91, end=139,
 anchor="'realm' f91; gap f104-126; 'one' f126",
 summary="The pull-back lands on the one realm: four towns joined by one four-colour road; the landscape breathes",
 audio_event="'realm' f91 (to f104). Music-only gap f104-126 (Dadd9 drone, -37 dBFS). 'one' f126 with a drone/bass re-swell (+12.5 dB).",
 visual_action="The pull-back eases out over the one realm in Bayeux idiom: multicolour hillock bands, a river in paired olive lines with a bridge, ploughed strips, four small walled towns (stitched elevations of settle_1/settle_2), each with a house-colour pennant, joined by ONE road couched in four alternating colours (gold, crimson, woad, green: Bayeux alternation as the image of unity) running to a crowned capital at centre. No titulus. In the gap the landscape breathes: as the key drifts az 120 -> 150 deg, relief rises 1.0 -> 1.4 -> 1.1, hills and towns lift a finger's breadth with lengthening soft shadows, then settle, the first promise that the cloth can wake. On 'one' f126 a slow truck right begins and tree divider T1 (interlace, trunk banded in the four house colours) crosses frame f126-139.",
 camera="Pull-back lands at F0 (3.3 px/mm) by f110 with ease-out; hold with 2 px/frame drift f110-125; truck right 0 -> 10 px/frame f126-139 (180-deg blur above 10). Key action inside x 320-2240 (4:3 safe).",
 technique="R25-F on the procedural Bayeux kit (albedo, height_mm, tangent, material, coverage, stitch_id at 6.6 px/mm); per-frame relight during the breath (height scale animated in the shader, so cast shadows lengthen); shared low-frequency fold field. Town elevations: game OBJs rendered side-on as flat colour-ID stills, re-stitched by the kit. COMP grade/grain. Gate G1: this shot is proved side by side with p1 at matched px/mm and identical relight before any other procedural section is built.",
 material_behavior="Narrative register: matte wool laid-and-couched fills with the couching-bar shadow grid (the Bayeux signature) under the 22-deg key; stem-stitch outlines with 0-1 mm linen gaps; linen 40-55 % of frame; Act I dyes near fresh values; pennants slightly raised satin (heraldic).",
 transition_out="T1 tree-divider splice: 8-frame match dissolve on the identical tree into p1.",
 emotional_purpose="Plenitude and unity: one land, one road, all four colours in balance.",
 est_render_cost="R25-F 49 frames x ~5 s = ~4 CPU-min (kit build is prep, gated by G1).",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S03", name="One table, one oath", act="I Oath", start=140, end=211,
 anchor="'table' f140; 'oath' f173; near-silence f185-198",
 summary="p1 slides in; the stitched table candles light and their pools bloom",
 audio_event="'table' f140 (accent); 'one' f162, 'oath' f173 (to f184); near-silence f185-198 (-45 dBFS); +10 dB in-gap swell f198-212 (bass f201).",
 visual_action="p1, the king and four lords at the oath table, slides in. Anticipating 'table', the two stitched candle flames on the table light one by one, left then right (f134-146): laid-strand flames that emit, warm 1900 K pools blooming on the linen around them (the film's first practical light). 'one oath' f167-181: the pools steady over the hands joined on the sword (light only, no metal glint). f185-198: everything holds, only the flames breathe. On the swell f198-212 both flames lift and brighten.",
 camera="Truck decelerating 10 -> 2 px/frame while pushing F0 -> F1 (3.3 -> 4.65 px/mm); p1 fills the frame width by f200; 2 px/frame drift in the near-silence.",
 technique="R25-F on p1 re-embroidered by relight25d (tiled bake at 10 px/mm with ~15 min of art-direction hints; phase-field stitch directions where the structure tensor is incoherent). Flame layer animated on twos as laid strands; each flame is also a point light in the relight (inverse-square pool, flicker 1-3 Hz + 8-12 Hz at 6-12 %).",
 material_behavior="Needle-painted fills re-embroidered as wool strands with fuzz; flames sway 2-4 Hz with outer strands lagging; candle pools warm the linen within ~20 cm.",
 transition_out="Continuous.",
 emotional_purpose="Ceremony and bond: the litany lands on light beats instead of cuts.",
 est_render_cost="R25-F 72 x ~5 s = ~6 CPU-min (p1 bake ~8 min + hints, shared with S04-S06, S09-S11).",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S04", name="One crown", act="I Oath", start=212, end=275,
 anchor="'crown' f230; gap f248-276",
 summary="Push to the king; metal flare 1 of 3 on the crown",
 audio_event="'one' f212, 'crown' f230 (attack f229, to f248). Music-only gap f248-276 (-32.8 dBFS), crescendo peaking f271.",
 visual_action="Slow push toward the king. On 'crown' (f224-236) METAL FLARE 1 of 3: the crown's couched gold flares (reaching #FFF3D6 for 2 frames at f230) and a glint circles the circlet once. Through the gap the light is at its warmest: purple king, four house tunics in balance; nothing else moves.",
 camera="Exponential push 1.00 -> 1.12x centred on the crown, the king held on the right third to break p1's symmetry; 2 px/frame drift.",
 technique="R25-F with the metal environment term (warm studio-gradient lobe so the crown reads as metal at the key azimuth); art-directed crown mask so the fleurs-de-lis do not dissolve into couched rows.",
 material_behavior="Metal glint confined to the crown (< 1 % of pixels); royal purple (madder over woad) reserved for the king; wool sheen <= 0.06.",
 transition_out="Continuous.",
 emotional_purpose="The height of the golden age: authority, warmth, order.",
 est_render_cost="R25-F 64 x ~5 s = ~5 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S05", name="They raised their cups", act="I Oath", start=276, end=338,
 anchor="'raised' f285; 'cups' f308",
 summary="First tiny awakening: the four goblets lift out of the cloth on thread tethers",
 audio_event="'They' f276, 'raised' f285 (bass f296), 'their' f299, 'cups' f308 (attack f307, to f322). Gap f322-339 (bass blip f323).",
 visual_action="Pull back to the whole table. First awakening, tiny: the four gold goblets lift 10-12 mm out of the cloth (anticipation dip f280, rise f283-292 on twos, staggered 2 frames left to right). Their stitches tauten into thread tethers, contact shadows open beneath, and where they lay the linen shows protected unfaded ground, needle holes and an underdrawn outline. They hang at the top of the lift on 'cups' f308.",
 camera="Exponential pull-back 1.12 -> 1.00x to full p1 (F1).",
 technique="R25-L frontal slip lift (camera <= 5 deg off the cloth normal, so slab side walls never show): goblet slips cut from the p1 maps; lift = 4-8 px parallax + 1.5 % scale + PCSS shadow whose penumbra widens with lift + contact AO; tethers from the R25 fibre/curve renderer; base patch = protected linen + needle-hole height field.",
 material_behavior="Tethers are wool strands catching a 25 % rim light; linen lips round the needle holes; goblet gold kept at level L1 (soft sheen, no travelling glint).",
 transition_out="Continuous.",
 emotional_purpose="Celebration, and the first sign that the cloth is alive.",
 est_render_cost="R25-L 63 x ~6 s = ~6 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S06", name="And swore it would never end", act="I Oath", start=339, end=445,
 anchor="'swore' f349; 'end' f391; gap f402-446",
 summary="Goblets settle; the gold thread runs on out of frame; the light cools; T2 splice",
 audio_event="'and' f339, 'swore' f349 (strongest early drone swell f358), 'it' f367, 'never' f381, 'end' f391 (to f402). Music-only gap f402-446 (1.46 s, Dmaj7; bass f428).",
 visual_action="On 'swore' the goblets settle back into the cloth on twos (f349-357), tethers slackening. The camera releases rightward along the upper border following the gold chronicle thread, which runs on and on out of frame ('never end') under a soft travelling sheen (L1). In the gap the light cools and sinks (3000 -> 1900 K, elev 22 -> 12 deg, -0.7 EV) and the candle pools contract. Tree divider T2 (dark woad bands) crosses frame f428-445.",
 camera="Pull back F1 -> F0 (f339-380); truck right 0 -> 12 px/frame (f350-400), held at 12 px/frame with 180-deg blur across the divider.",
 technique="R25-F, relit per frame only during the light change; cached plates moved in 2D elsewhere.",
 material_behavior="Dye warmth drains as the light cools; the thread's sheen leads the eye right.",
 transition_out="T2 tree-divider splice (8-frame match dissolve f438-445) into p3.",
 emotional_purpose="Confidence curdling into foreboding: the promise outruns the frame while the light dies.",
 est_render_cost="R25-F 107 x ~4 s = ~7 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S07", name="Then the king died", act="II Death", start=446, end=497,
 anchor="'king' f458; 'died' f469; drone -6 dB f480",
 summary="p3, the king on his bier; a stitched candle flame is unpicked on 'died' and its light leaves the cloth",
 audio_event="'Then' f446, 'the' f453, 'king' f458, 'died' f469 (to f483); the D drone starts to exit (-6 dB f480); bass f495.",
 visual_action="p3: the king lies in state on the purple bier, night-blue ground, four tall stitched candles. Act II light: one cold candle key at 12 deg, saturation 0.7, only the crown carries gold. On 'died' (f465-471) the nearest candle's stitched flame is unpicked: its threads drawn out in reverse stitch order over 6 frames, curling up to 20 mm before they vanish, leaving needle holes and a bare underdrawn flame. Its light leaves the cloth (-0.5 EV). The drone, the floor of the score, follows it out from f480.",
 camera="F1; truck decelerating 12 -> 2 px/frame, landing on 'died'; then 2 px/frame drift.",
 technique="R25-F on p3 re-embroidered (tiled bake 10 px/mm) + R25-S unpick (stitch_id threshold run backwards, snapshot re-raster every 2 frames, loose ends from the fibre/curve renderer); the flame's point light is removed from the relight over the same 6 frames.",
 material_behavior="Unpicked strands kinked where they were couched and hairier at the cut ends; holes are dark pits with raised linen lips; the crown keeps the only gold.",
 transition_out="Continuous.",
 emotional_purpose="Death told by the cloth losing a light, not by melodrama.",
 est_render_cost="R25-F/S 52 x ~6 s = ~5 CPU-min (p3 bake ~8 min).",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S08", name="And left no heir", act="II Death", start=498, end=560,
 anchor="'heir' f522; drone gone f548; gap f532-561",
 summary="An underdrawn heir that was never stitched; the film's only titulus, SINE HEREDE",
 audio_event="'and' f498, 'left' f505, 'no' f515, 'heir' f522 (to f532). Drone -15 dB f534, gone by f548. Music-only gap f532-561 (F6, -28 dBFS) as the lament chords take over.",
 visual_action="The camera drifts past the foot of the bier into a narrow strip of bare linen between two blue-black couched bars. Here there is only the designer's underdrawing: a small crowned figure in faint brown ink that was never stitched, the heir who never was, and beneath it the film's only titulus, SINE HEREDE, in red-brown stem stitch. Nothing moves. As the drone disappears we stay on the unstitched figure. T3, a leafless winter tree in blue-black, crosses frame f548-560.",
 camera="F1 truck 2 -> 6 px/frame (slow, so the figure holds for ~1.5 s), 180-deg blur only across the divider.",
 technique="R25-F (underdrawing = warm-brown ink line with slight bleed into the weave, no relief; titulus from Cinzel 700 skeletons stem-stitched by the R25 titulus module, baseline wobble +/-0.8 mm).",
 material_behavior="Bare linen and ink: the absence of relief is the image. The titulus is the only wool in frame.",
 transition_out="T3 tree-divider splice (match dissolve f553-560) into the repeated oath table.",
 emotional_purpose="Vacancy: the score loses its floor exactly as the line of succession does.",
 est_render_cost="R25-F 63 x ~2 s = ~2 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S09", name="Every lord looked at the empty chair", act="II Death", start=561, end=716,
 anchor="'lord' f578; 'looked' f637; 'chair' f669; gap f681-716",
 summary="The oath table again, colder and tighter; the king is unpicked live; the crown is left hanging over a king-shaped void",
 audio_event="'and' f561, 'every' f567, 'lord' f578, 'who had sat' f591-607, 'at that table' f609-631, 'looked' f637, 'at the' f648-654, 'empty' f656, 'chair' f669 (to f681). Lament chords ~-28 dBFS; gap f681-716 (fullest music 23-25.5 s).",
 visual_action="The oath table again, further along the roll (Bayeux repeats scenes), unmistakably different at first sight: framed tight (1.15x panel-native) with the throne on the left third, a cold single-candle key at 12 deg, dyes aged and desaturated, the stitched table candles dark, and the four goblets gone, only their needle-hole outlines left. The king is still on the throne, and comes undone as we watch (f561-640): his couching bars release first, then his purple, ermine and beard strands slacken in a ripple, lift and curl 5-20 mm off the cloth and pull out through the linen, top to bottom, on twos. What remains on the throne is bare linen pricked with needle holes and the faint red-brown underdrawing of his silhouette: the empty chair is a king-shaped absence. The four lords and the throne stay. The crown (heraldic couched gold) is not unpicked: it hangs where his head was, lifted 10 mm, its soft shadow falling into the void. On 'looked' f637 the push begins; it lands on the void on 'chair' f669. Gap: hold; the crown turns very slightly on its thread.",
 camera="Locked at 1.15x with 1 px/frame drift (f561-636); exponential push 1.15 -> 1.35x (f637-669, within the 10 px/mm bake); hold with 2 px/frame drift through the gap.",
 technique="R25-F on the p1 maps with an Act II re-dye (aged values, sat 0.7) + R25-S unpick of the king's stitch_ids in top-to-bottom order (snapshot re-rasters, loose-end curls from the fibre/curve renderer, needle-hole and underdrawing reveal underneath); crown slip by R25-L frontal lift with PCSS shadow. Neither the broken p1_empty plate nor a second panel is used.",
 material_behavior="Unpicked wool crinkled and kinked where it was couched; 0.6 mm needle holes with a slight linen halo catch the raking light; underdrawing has no relief and no sheen; the crown is the only highlight.",
 transition_out="Continuous.",
 emotional_purpose="Absence: every gaze in the scene converges on a hole in the cloth.",
 est_render_cost="R25-F/S/L 156 x ~8 s = ~21 CPU-min; prep: king stitch order + unpick snapshots ~3 h.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S10", name="His own head beneath the crown", act="II Death", start=717, end=784,
 anchor="'own' f741; 'head' f753; 'beneath' f766",
 summary="The candle key swings; the crown's shadow crowns each lord in turn and leaves an underdrawn ghost crown",
 audio_event="'and' f717, 'saw' f724, 'his' f732, 'own' f741 (stressed), 'head' f753, 'beneath' f766, 'the' f780; low swell f750; the lament at its fullest.",
 visual_action="The candle key swings right to left (az 160 -> 40 deg over 2.3 s, decline). The hanging crown's long shadow slides across the linen and crowns each lord in turn: the gold tunic on 'own' f741, red on 'head' f753, blue on 'beneath' f766, green at f778. Where the shadow-crown touches, a ghost crown in faint red-brown underdrawing is left on the lord's head: the ambition drawn, never stitched. Four ghost crowns accumulate.",
 camera="Exponential pull-back 1.35 -> 1.05x (f717-740) so all four lords are in frame by 'own'; then locked with 1 px/frame drift.",
 technique="R25-F with per-frame relight for the moving key; crown shadow = slip alpha offset by lift/tan(elev) along the light vector, penumbra growing with distance; ghost crowns = intro/crown silhouette traced to running-line underdrawing, revealed in stitch order on twos (6 frames each).",
 material_behavior="The raking light walks across the couching bars, so the bar-shadow grid comes alive on the tunics; a small crown glint (L2) migrates as the light swings.",
 transition_out="HARD CUT on 'crown' f785, matched on the crown's screen position and light direction.",
 emotional_purpose="Ambition and inevitability: each lord sees himself crowned; the war is already decided.",
 est_render_cost="R25-F 68 x ~6 s = ~7 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S11", name="The oath unpicked", act="II Death", start=785, end=843,
 anchor="'crown.' f785; collapse f797-798; near-silence f797-843",
 summary="Macro: the crown's gold is ripped out as the music collapses; the last candle dies; near-black",
 audio_event="'crown.' f785-799. The music collapses ~20 dB at f797-798, the strongest internal boundary of the score. Near-silence f797-843 (-47 dBFS, Gm(add9) whisper).",
 visual_action="Extreme macro on the crown's couched gold, matched to the crown's position at the cut. f786: a hooked needle catches the gold pair. Tie-down stitches pop one after another (f786-797), wool fibres springing up, and on f797-798 the gold thread rips out through the linen and whips out of frame exactly as the music falls away. The candle dies with it: the key decays to a cold graze (-4 EV) by f812. What remains: empty needle holes, crushed fibres, the dent the thread left. f813-843: near-black (floor #07070A, cool fill #141325 at 10 %); only one loose thread end settles. An invisible splice in the dark at f820 moves us to the linen of the war strip. From f832 a low ember glow rises from the bottom edge of frame. The chronicle thread itself is untouched: only the crown's gold is torn.",
 camera="Macro ~48 mm field, f/8, cloth tilted 15 deg; whip-follow of the escaping thread f790-798 with motion blur; then locked, 1 px/frame drift. The tightest framing of the film sits on its quietest sound.",
 technique="EV-DM macro rig E0 reused: Eevee 1920x1080 16 TAA on ones f785-812 (28 renders): crown gold as a padded couched pair over displaced linen, tie-downs as small curves with pop animation, the thread an animated curve sliding along its path. f813-843 COMP hold on the last render with light decay and grain. War-linen macro rendered as 2 Eevee stills with split lights (cool fill, ember) mixed in COMP for the rising glow.",
 material_behavior="Heraldic padded gold tears free; linen shows holes with the thread's dent still in them; the metal glint dies to nothing; then only the weave relief reads.",
 transition_out="Darkness; the ember glow becomes S12's firelight (continuous).",
 emotional_purpose="The oath breaks, and the silence is the shock.",
 est_render_cost="Eevee E0 28 renders + 2 light-split stills @1080p (~65 s) = ~33 min; COMP 31 frames.",
 eevee=dict(block="E0", r1080=30, r1440=0)),

dict(id="S12", name="The wars lasted a hundred years", act="III War", start=844, end=924,
 anchor="'wars' f850; 'lasted' f867; 'hundred' f884; 'years' f899",
 summary="Out of the weave onto the war strip: slips stand up out of the cloth, clash once, and freeze while a hundred years age the cloth",
 audio_event="'The' f844, 'wars' f850, 'lasted' f867, 'a' f881, 'hundred' f884, 'years' f899 (stressed, to f916), 'and' f918. Music at or below -45 dBFS (thin, airy, no bass); crescendo from f896.",
 visual_action="Firelight grazing from the bottom edge of frame (2200 K, 2-6 Hz flicker at 15-25 %) rakes a macro of linen: every warp and weft thread throws a long shadow. We glide slowly between the ridges (f844-860) and rise over one of them (f856-878) to find the war strip lying flat: a madder dusk sky over hillocks, two armies of stitched slips in the cloth, the merchants' blue facing right to left against the reading direction, the legion's crimson facing them, far horse legs in alternating colours. 'lasted' (f867-884): the front ranks stand up out of the cloth: each slip hinges at its feet to ~70 deg like the game's figure cards, felt edge showing, its stitches stretching into thread tethers that snap one by one, long shadows thrown away from the fire. 'hundred' f884: a single clash (strike poses on twos with a 0.12 s lunge, game timing), then they freeze mid-strike. 'years' (f899-918): a hundred years pass in the light: the firelight pulses through dozens of day-night cycles while the cloth ages around and under the frozen soldiers (dyes bleach, foxing and a tideline bloom, tethers sag) and the gold chronicle thread in the upper border tarnishes (#E9BE6A -> #7A5A2A). One generation only; nothing else moves.",
 camera="Macro dolly at F3 (~50 mm field, f/8, cloth 20 deg to the lens) f844-860 at <= 6 px/frame; slow crane up and back to F1 at a 22-deg oblique (f856-878), the only oblique in the narrative register and inside the 25-deg rule; then locked in 3D, with a 2D drift right to left at 2-3 px/frame and a 3-deg dutch on a 15 % overscan; from f918 the crane back to face-on starts (see S13). No fast moves under the near-silence.",
 technique="EV-DM block E1: Eevee 1920x1080, 16 TAA in macro / 8 TAA wide. War strip = displaced mesh from R25 maps of war_bg re-embroidered; figure slips from R25's figure builder (tex_tinted albedo + normal + mask; all 11 units x idle/strike x 4 realms pre-baked as a batch; Legion livery in game crimson with a couched-gold cross shield) exported as 1.5 mm padded cards with a solidify felt edge and foot hinges; tethers as bevelled curves with snap animation; area light from the bottom edge; real DOF in macro. On ones f844-871 (28 renders), on twos f872-916 (23 renders). The ageing time-lapse is done in COMP by re-texturing the ground through Eevee's UV and shading-ratio passes with 6 keyed R25 ageing states, so it needs no extra renders.",
 material_behavior="Figure satin (mask B channel) catches the firelight; wool fuzz haloes glow on the risen slips' edges; the ground is matte; thread boil on twos only on moving figures; dyes visibly age.",
 transition_out="Continuous into S13 (the crane to face-on starts f918).",
 emotional_purpose="Violence without progress: a war fought in silence that only ages the cloth.",
 est_render_cost="Eevee E1 51 renders @1080p (28 x ~65 s macro + 23 x ~15 s) = ~36 min; COMP 81 frames.",
 eevee=dict(block="E1", r1080=51, r1440=0)),

dict(id="S13", name="And ended nothing", act="III War", start=925, end=981,
 anchor="'ended' f925; 'nothing' f942; silent gap f952-979",
 summary="The soldiers topple and are unpicked at once; a field of needle holes under grazing light in silence",
 audio_event="'ended' f925, 'nothing' f942 (to f955). Near-silent gap f952-979 (-47 dBFS).",
 visual_action="'ended' (f925-940): the soldiers topple back flat into the cloth one by one, slowly, like falling cards, while the camera cranes up to face the cloth. 'nothing' f942: every figure is unpicked at once, threads withdrawn along their outlines in a single breath (f942-952). Left behind: aged linen pocked with needle holes in the shapes of men and horses, snipped ends, faint underdrawn ghosts. In the silent gap the frame is still and tight: a slow grazing light (elev 6 deg) slides across the hole field and every hole casts a tiny shadow. f975-981: at the right edge the linen begins to brown; a scorch is coming.",
 camera="Eevee crane from the 22-deg oblique to face-on (f918-943, eased, ~0.9 deg/frame); then locked at F1 with a slow push 1.00 -> 1.06x through the gap (tight framing on the quiet).",
 technique="EV-DM E1 on ones f918-943 (26 renders); registered swap to R25 at zero tilt f940-944 (same maps; median dE_ok x100 < 2, no edge shift > 1 px); R25-S mass unpick (snapshot re-rasters every 2 frames) + R25-F relight of the hole height field under the moving grazing light; scorch start = R25 burn mask.",
 material_behavior="Holes as relief (0.3 mm pits with raised lips), loose fibres rim-lit, all wool gone; the hundred-year ageing remains on the linen.",
 transition_out="The scorch carries into S14.",
 emotional_purpose="'Nothing' made visible: a hundred years leaves only holes.",
 est_render_cost="Eevee E1 26 renders @1080p (~15 s) = ~7 min; R25-F/S 42 frames x ~6 s = ~4 CPU-min.",
 eevee=dict(block="E1", r1080=26, r1440=0)),

dict(id="S14", name="Cities fell to ruin", act="III War", start=982, end=1050,
 anchor="'Cities' f982; 'fell' f999; 'ruin' f1015; pad returns f1017",
 summary="The scorch burns through; across the hole onto p6, the burning city; towers fall; the stitched fire scorches the real linen",
 audio_event="'Cities' f982 (attack f987), 'fell' f999, 'to' f1009, 'ruin' f1015 (to f1028). Soft pad returns f1017 (+5 dB). Near-silence f1029-1047, gap to f1051.",
 visual_action="On 'Cities' the scorch spreads across the hole field from the right, p6's fire reaching back along the roll: linen browning to soot, a glowing ember rim, laid-strand flames licking its edge. It burns right through to the dark walnut beneath, and the camera trucks across the burnt hole (ember-rimmed dark, f988-997) onto p6, the walled city in flames. 'fell' (f999-1010): the cracked towers' upper sections drop on twos as rigid cut-outs (3 frames per pose) while their masonry stitches unpick. 'ruin' f1015: the torn banner at the gate slumps. As the pad returns (f1017) the stitched flames quicken (2 -> 4 Hz) and begin to scorch the real linen of the panel's margins, browning and small ember-rimmed holes creeping into the border: the chronicle consumed by what it depicts. Near-silence f1029-1047: only flames and stem-stitch smoke spirals turning (10-20 deg/s). f1040-1050: a charred interlace tree crosses frame as the truck resumes.",
 camera="Truck 0 -> 10 px/frame f984-992 (180-deg blur) across the burnt hole, decelerating to 2 px/frame by f1006; F1, 2-3 deg dutch, firelight from the bottom edge; locked drift; ease back in from f1038 for the divider.",
 technique="R25-F on p6 re-embroidered + R25 burn mask (noise-advected distance field: linen -> foxing #9C7046 -> soot #3A3330 -> char, 1-3 px ember rim #DE6A2C -> #F6B54A flickering, curled edge as a relit height lift). The dark burnt hole hides the splice. Tower cut-outs, flames and smoke on twos. No particles. Burn and soot maps persist as ageing layers through S15-S18.",
 material_behavior="Fire is wool and smoke is stem stitch; wool fills singe faster than outlines; the ember rim is the only emissive.",
 transition_out="Charred tree-divider splice into S15.",
 emotional_purpose="Loss of civilisation made tactile: the cloth itself burns.",
 est_render_cost="R25-F 69 x ~6 s = ~7 CPU-min (p6 bake ~8 min; burn sim prep ~3 h).",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S15", name="Roads swallowed by the forest", act="III War", start=1051, end=1137,
 anchor="'Roads' f1051; 'swallowed' f1075; 'forest' f1101",
 summary="The four-colour road of the one realm returns, and the forest stitches over it",
 audio_event="'Roads' f1051 (stressed), 'were' f1068, 'swallowed' f1075, 'by the' f1092-1099, 'forest' f1101 (to f1115). M4 pad plateau ~-40 dBFS (Dm add9). Gap f1115-1137.",
 visual_action="Beyond the charred tree the four-colour road of the one realm (S02) returns as a rhyme: faded, broken, its couching loose, singed where the fire reached. Interlace trees stitch themselves over it: stem-stitch tendrils creep along the road from both borders, couched leaves bloom in olive/sage/forest alternation and banded trunks rise, each stitch led by a steel needle glint at its growing tip. On 'forest' f1101 the last stretch of road disappears. In the gap the forest thins.",
 camera="Truck right 6 -> 4 px/frame at F0. The firelight sinks to an ember glow from the bottom edge; a cool dusk fill rises.",
 technique="R25-S procedural stitch-on: vector trees -> stitch maps with stitch_id in needle-path order (spatial adjacency), each strand growing along its length with a pop-in height curve, 20-60 mm/s physical, laid -> bars -> tie-downs -> outline; dirty-rect recompute of normals/AO/fibres; R25-F relight.",
 material_behavior="Fresh green wool, slightly proud and unaged, over faded road dyes and the S14 scorch.",
 transition_out="Tree-divider splice f1120-1137 into the four towns.",
 emotional_purpose="The world returning to wildness; the paths between people close.",
 est_render_cost="R25-S/F 87 x ~6 s = ~9 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S16", name="Men forgot their own borders", act="III War", start=1138, end=1253,
 anchor="'forgot' f1149; 'beyond' f1182; 'borders' f1211; gap f1229-1253",
 summary="Bars wall the strip into cells; the road is snipped; each town's road is re-couched as a closed cord in its realm colour; fog quilts cover the rest",
 audio_event="'Men' f1138, 'forgot' f1149, 'what' f1166, 'lay' f1173, 'beyond' f1182, 'their' f1196, 'own' f1201, 'borders' f1211 (stressed, to f1229). Gap f1229-1253 (D7 colour, in-gap swell from f1241).",
 visual_action="Four small walled towns along the register, one per house (stitched elevations of settle_0/1/2), still joined by the last of the four-colour road. 'forgot' (f1149-1165): vertical couched bars stitch themselves down between them like walls (the Bayeux compartment device, alternating slant), snipping the road at every bar; the cut ends curl. 'what lay beyond' (f1166-1195): the land between the towns bleaches back toward underdrawing and quilted cloud appliques (the game's own fog-of-war kit) slide in over it from the bars. 'own borders' (f1201-1211): each town's road segment is pulled into a closed ring and re-couched as a single cord in its realm colour (gold, crimson, royal blue, green): the game's border idiom, a thick running-stitch cord between brown edgings. The last ring closes on 'borders' f1211. Gap: four towns, four colours, four rings, fog between them.",
 camera="F0; truck 4 -> 1 px/frame by f1180, then locked with 1 px/frame drift. No move into the bass yet.",
 technique="R25-S stitch-on (bars, cords) and unpick (road snips, bleach-back) driven by stitch_id masks; cloud_puff_1-8 / cloud_edge_1-3 / cloud_corner_in/out as height-mapped padded layers relit by R25 (luminance-derived normals); COMP.",
 material_behavior="Couched bars alternate blue-black and red-brown; realm cords are wool/silk with 10-15 % sheen; fog quilts are cream cotton with brown running-stitch outlines puffing 2-3 mm.",
 transition_out="Continuous.",
 emotional_purpose="Suspicion and small worlds: the one realm splits into the game's four.",
 est_render_cost="R25-S/F 116 x ~6 s = ~12 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S17", name="And the world grew...", act="III War", start=1254, end=1282,
 anchor="'world' f1263; 'grew' f1281; bass enters f1283",
 summary="Held breath before the bass: embers gutter, fog thickens, the first weft threads lift",
 audio_event="'and' f1254, 'the' f1258, 'world' f1263 (stressed), 'grew' f1281. In-gap swell f1241-1257; music creeping up to ~-36 dBFS. The bass enters on the next frame.",
 visual_action="A held breath. The ember glow gutters lower, the fog quilts thicken at the margins, and the first weft threads at the cloth's top and bottom edges loosen and lift. Nothing travels.",
 camera="Locked, 1 px/frame drift. Nothing launches before f1283.",
 technique="R25-F relight with a falling key; fray masks begin (R25 fibre/curve renderer).",
 material_behavior="Loosened weft with fuzz catching the last warm light.",
 transition_out="Continuous into the pull-back on the bass.",
 emotional_purpose="Dread contracting: the stillness before the drop.",
 est_render_cost="R25-F 29 x ~4 s = ~2 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S18", name="Dark at its edges", act="III War", start=1283, end=1381,
 anchor="BASS ENTRY f1283; 'dark' f1292; 'edges' f1319; bass f1345; swell f1372",
 summary="On the bass the camera pulls back: the strip on a dark walnut table, fraying into darkness; one gold glint survives",
 audio_event="BASS ENTRY f1283 on 'grew' (+26 dB in 22-120 Hz, the biggest musical event). 'dark' f1292, 'at its' f1308-1318, 'edges' f1319 (to f1336). Gap f1336-1381 (-31.9 dBFS) with bass pulse #2 at f1345 and an in-gap swell into 'Now' from f1372.",
 visual_action="On the bass the camera pulls back: the chronicle is revealed as a long strip lying along a dark walnut table, both ends lost in darkness, and its edges are dying. Borders fray, weft threads pull loose and curl, the border beasts unravel into fringe, fog quilts roll in from the margins over the strip. On 'dark' f1292 the ember glow dies. By 'edges' f1319 the fraying bites into the main register and the light falls off to -2.5 EV at the frame edges (physical falloff, not an overlay). Gap: stillness. At the far right end of the strip a single gold glint survives (the chronicle thread, unbroken) and it pulses once on the bass f1345. From f1372 a faint pre-dawn lift (cool grey-blue fill from the left, +0.3 EV) anticipates 'Now'.",
 camera="Exponential pull-back F0 3.3 -> 0.75 px/mm (4.4x) launching on f1283 (6-frame ease-in, cruising by 'dark' f1292, ease-out by f1360; frame-edge texture <= 24 px/frame with blur), slight rise; hold f1360-1381.",
 technique="R25-F on a long plate assembled from every section plate at ~1.5 px/mm (weave LOD-faded); animated fray masks + fringe curves from the R25 fibre/curve renderer; cloud-kit layers; physical light falloff in the relight; procedural walnut (R25 wood albedo/height).",
 material_behavior="Fraying weft and loose fibres rim-lit by the last light; aged dyes; a single L2 metal glint pulse.",
 transition_out="Continuous; the glint carries the eye into S19.",
 emotional_purpose="Despair and smallness, and one thread of hope that did not break.",
 est_render_cost="R25-F 99 x ~4 s = ~7 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S19", name="Now every ruler believes...", act="IV Renewal", start=1382, end=1523,
 anchor="'Now' f1382; 'ruler' f1407 + bass f1410; 'whole' f1466 + bass f1471; Bb gap f1491-1523",
 summary="Dawn sweeps L->R: fog peels, the cloth mends, dyes revive, four crests stitch on; metal flare 2 of 3 on 'whole'",
 audio_event="'Now' f1382, 'every' f1395, 'ruler' f1407 (bass pulse f1410), 'believes' f1419 (stressed), 'the world' f1432-1445, 'can be made' f1447-1464, 'whole' f1466 (bass pulse f1471), 'again' f1477 (to f1491). Gap f1491-1523: sustained Bb3 horn/choir over Bbmaj7, the brightest, most hopeful colour of the score.",
 visual_action="On 'Now' dawn (4300 K) breaks from the left and sweeps left to right across the strip over 3 s. Where it passes, the fog quilts peel back toward the margins (the game's own fog reveal), the cloth mends (fringe re-weaves into the edges, holes are darned closed in fresh, visibly mismatched thread #E2DBC6) and the dyes revive from aged to fresh (OKLab, staggered 0.2-0.4 s per region behind the light). 'every ruler' (f1395-1415): the four house crests stitch on in the upper border near the strip's end, padded satin with couched gold over the padding (builders' gold hammer, legion's red eagle, merchants' blue scales, nomads' green raven and horse), one every 5 frames, the last landing on the bass f1410, each flashing block by block as the light crosses it. 'whole' f1466: METAL FLARE 2 of 3, the chronicle thread is re-couched end to end, its tarnished stretch replaced, a glint running the visible length. Bb gap: arrival at the end of the written chronicle in full dawn; beyond it, fresh linen with only faint ink underdrawing.",
 camera="Exponential push back in 0.75 -> 4.0 px/mm (f1382-1490) while trucking right toward the strip's end (~1.2 m of cloth), motion blur wherever frame edges exceed 12 px/frame; then truck 6 -> 4 px/frame in the Bb gap.",
 technique="R25-F with the S18 masks run in reverse (unfray, unfog), per-region aged -> fresh albedo lerp keyed to the light front, crests re-embroidered from ui/crest_* as heraldic padded satin (<= 1.2x native), metal environment term for the flare; COMP.",
 material_behavior="Colour revival is the visual metaphor for 'made whole'; heraldic satin blocks flash separately; fresh darning visibly mismatched; wool sheen rises with the key.",
 transition_out="Continuous.",
 emotional_purpose="Hope and ambition: the world and the cloth are mended together.",
 est_render_cost="R25-F 142 x ~6 s = ~14 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),

dict(id="S20", name="One banner", act="IV Renewal", start=1524, end=1558,
 anchor="'banner' f1533; bass pulse f1536",
 summary="In the unwritten end of the roll, one banner rises out of the cloth on the bass",
 audio_event="'One' f1524, 'banner' f1533 (to f1544), bass pulse f1536; crescendo f1520-1550.",
 visual_action="Past the last stitched scene lies the unwritten remainder of the roll: fresh linen with only the designer's underdrawing, a hex lattice, a coastline, the outline of a realm (the game board's layout). In it one banner lies stitched flat: a couched gold pole and the builders' gold flag with its red hammer. From f1527 its stitches tauten; on the bass f1536 the tethers snap one by one and it rises out of the cloth, hinging upright, the flag unfurling in the raking dawn. It then sways with the music's 2.115 s pulse.",
 camera="Truck right 4 -> 2 px/frame at ~4 px/mm, decelerating into the board's zero-tilt pose: a perspective rostrum camera looking straight down with the menu's 30-deg vertical FOV, pivot on the menu camera's target near Grandbois, so risen pieces show real parallax.",
 technique="EV-DM block E3: Eevee 1920x1080 16 TAA on ones (camera moving), risen piece stepped on twos. Ground = displaced mesh from R25 maps of the remainder (fresh linen + underdrawing); settle_banner OBJ with a stitched material (palette albedo, triplanar stitch normal, brown inverted-hull cord as the game's piece outline); its unrisen state registered to its own R25 footprint so the swap is invisible; tethers as bevelled curves.",
 material_behavior="Banner silk with a satin sheen; small gold glint on the pole (L1-L2); tethers recoil when released; the needle-hole footprint stays visible where it lay.",
 transition_out="Continuous.",
 emotional_purpose="A single act of will: the player's first gesture, foreshadowed.",
 est_render_cost="Eevee E3 35 renders @1080p 16 TAA (~25 s) = ~15 min; COMP 35 frames.",
 eevee=dict(block="E3", r1080=35, r1440=0)),

dict(id="S21", name="One village", act="IV Renewal", start=1559, end=1598,
 anchor="'village' f1569; gap f1583-1598",
 summary="Beside the banner, one village rises out of its stitched footprint in two stop-motion steps",
 audio_event="'one' f1559, 'village' f1569 (to f1583). Gap f1583-1598 (0.52 s, Dm add9).",
 visual_action="Beside the banner, on the hex where Grandbois will stand, a village stitched in plan (roof tiles laid in alternating madder and terracotta, blue-black stem-stitch walls) rises in two stop-motion steps on 'village' (f1563-1575): walls extrude from their stitched footprints, houses pop up row by row on twos, tethers snap free. The dawn key (elev 28 deg) throws lengthening cast shadows, the main depth cue under a top-down camera. Every piece shows tethers, a contact shadow and its needle-hole footprint for at least 6 frames. The hex underdrawing around it stays unstitched.",
 camera="Drift 2 -> 1 px/frame; same zero-tilt perspective camera (real parallax between roofs and ground).",
 technique="EV-DM E3 (same scene): settle_1 OBJ, roofs projected with exactly the 2D stitch texture they had when flat, walls with synthesised laid-and-couched stitches at the same mm scale; contact shadows; tethers as curves.",
 material_behavior="Roofs keep exactly the stitch texture they had when flat; new side walls carry stitches at the same mm scale (no stretched pixels).",
 transition_out="Continuous.",
 emotional_purpose="The first home: growth after ruin.",
 est_render_cost="Eevee E3 40 renders @1080p (~25 s) = ~17 min; COMP 40 frames.",
 eevee=dict(block="E3", r1080=40, r1440=0)),

dict(id="S22", name="One blank page", act="IV Renewal", start=1599, end=1688,
 anchor="'one' f1599 + bass; 'blank' f1614; 'page' f1630; bass f1664",
 summary="The gold thread frames a separate leaf of blank cloth; a blank world lies beyond; the first candle is relit",
 audio_event="'one' f1599 (bass pulse +21.6 dB), 'blank' f1614, 'page' f1630 (to f1645). Gap f1645-1688 (Dm add9), bass pulse f1664, in-gap swell f1658-1692.",
 visual_action="On 'one' the gold chronicle thread leaves the restored border, runs down across the blank end of the roll and couches a rectangular frame round a leaf of fresh cloth on the left (its glint racing round, L2, f1600-1628): a separate, finer leaf tacked into the roll by the couching, its hem casting a hairline shadow. On 'page' f1630 the frame closes and the light settles on it; a faint drypoint ruling (one title line and one rule) catches the light. Nothing else is written. To the right, the hex underdrawing runs unstitched to the end of the roll, a blank world as well as a blank page, with the banner and the village standing alone in it. Gap: stillness; on the bass f1664 a warm candle pool blooms from off-frame left across the leaf, the first candle lit since the oath broke. The thread's end rests at the leaf's corner, waiting.",
 camera="The truck eases to a full stop by f1612 on the exact E4 zero-tilt pose; locked thereafter (registration to the menu starts here).",
 technique="R25-S thread couching (needle-path order, travelling glint) and drypoint ruling as embossed hairlines in the height map; the banner/village layer is one E4 zero-tilt still at 1440p (pieces are static); candle pool = a warm point light in the R25 relight (inverse-square, flicker 1-3 Hz + 8-12 Hz at 6-12 %); COMP. E3 renders run to f1612 (14 renders) for the last of the camera move.",
 material_behavior="The leaf's albedo is the game's parchment-interior art (inpainted from the native menu capture) carrying fresh-linen micro-relief that reads only in raking light: at this scale the weave is below Nyquist and LOD-faded (bible section 3), so leaf and parchment are one material and nothing morphs later. Gold cord raised 0.6 mm.",
 transition_out="Continuous (same framing).",
 emotional_purpose="Possibility and invitation: the space left for the player.",
 est_render_cost="Eevee E3 14 renders @1080p = ~6 min; R25-S/F 90 x ~5 s = ~8 CPU-min; 1 E4 zero-tilt still (counted under S23).",
 eevee=dict(block="E3", r1080=14, r1440=0)),

dict(id="S23", name="When this age is remembered", act="V Question", start=1689, end=1743,
 anchor="'age' f1707; 'remembered' f1726 + bass pulse #8",
 summary="The thread embroiders the board; the leaf lifts as a lectern while the camera cranes and the board wakes",
 audio_event="'When' f1689, 'this' f1698, 'age' f1707, 'is' f1719, 'remembered' f1726 (to f1744) with bass pulse #8 at f1726; building toward the climax.",
 visual_action="f1689-1711: the thread runs on from the leaf's corner into the hex underdrawing and the board is embroidered before our eyes: it couches the gold realm border along the hex lines, satin hex fields fill hex by hex in a wavefront spreading right and back (greens, wheat, ochre), the sea floods in stitched denim blue (#316994) with wave marks, flat plan-icon towns stitch in; the wave's frontier shows the underdrawing continuing on bare linen. On 'age' f1707 a second warm pool blooms from off-frame right: both candles burn again. 'remembered' f1726 (bass): the thread pulls its couching out of the leaf's three free edges and the leaf lifts off the cloth, hinged on its still-tacked bottom edge, tilting up exactly as the camera begins to crane, so it stays square to the lens like a reader's lectern, with a widening contact shadow beneath. Behind it the board starts to tilt and wake: fields swell 1-2 mm as padded coupons (capitonnage, seams pinching and darkening), forests rise as stitched cones, towns and figure groups begin to rise out of their stitched footprints on twos with tethers releasing, and the village grows (settle_1 -> settle_2) toward Grandbois.",
 camera="Locked until f1725. From f1726 a 3D crane about the menu camera's target, tilt 0 -> 24 deg (pitch 90 -> 66.09), eased, converging on the game's menu camera (vertical fov 30 deg, distance 20.9).",
 technique="f1689-1711 R25-S 2D stitch-on of the board in plate-UV space (per-hex delay map) under a moving 4300 -> 3200 K raking key. f1712-1725 registered 14-frame swap to the zero-tilt Eevee render (identical albedo + baked stitch normals; median dE_ok x100 < 2, no edge shift > 1 px). From f1712 EV-DM block E4 hero: Eevee 2560x1440, 16 TAA, on ones; board proxy plane with per-hex puff shape keys (dome + seam pinch) + the decoded game OBJs at their world positions; ground UVs from the overscanned top-down/UI-free plates; a pieces-hidden plate under rising pieces; the leaf as a separate holdout layer + shadow catcher (also rendered at its 4:3 position).",
 material_behavior="Satin hex fields (silk lobe exp 40, sheen per block), couched gold borders, denim sea with stitched waves: the game's own embroidery language arrives; puffed coupons with cream running-stitch seams over a dark groove; wool sheen at grazing angles.",
 transition_out="Continuous.",
 emotional_purpose="Lift-off and recognition: the chronicle turns into the game.",
 est_render_cost="R25-S 23 x ~8 s = ~3 CPU-min; Eevee E4 32 hero renders (f1712-1743) + 1 zero-tilt still @1440p (~95 s) = ~52 min.",
 eevee=dict(block="E4", r1080=0, r1440=33)),

dict(id="S24", name="Climax: the cloth becomes the board", act="V Question", start=1744, end=1782,
 anchor="climax gap f1744-1783; bass swell f1755; peak f1760",
 summary="Everything rises; the crane lands on the menu camera; the chronicler's furniture assembles round the board; the valance unrolls blank",
 audio_event="Music-only climax gap f1744-1783: the loudest music of the piece (-25.6 dBFS, Bbmaj7/F6), bass swell f1755, peak f1760.",
 visual_action="Everything wakes at once: towns, castles, farms, forests and figure groups rise out of the cloth staggered outward from Grandbois, rigid, on twos, each with tethers, contact shadow and needle-hole footprint for at least 6 frames, all settled by f1760; the village has become Grandbois under its banner. The crane completes onto the exact menu camera (within 0.3 deg by f1760, exact at f1766). A warm 3200 K light sweep crosses the board left to right, peaking mid-frame at f1760: satin fields flash block by block and the couched gold realm borders glint in sequence (L2, capped; not a flare). As the camera arrives, the chronicler's furniture assembles round the board through the camera's own motion: the walnut beam with its rolled valance along the top, the blue-lion and red-lion banners swinging into the top corners, the two candles (already burning) at the sides, the carved lions rising into the lower corners, and the walnut reading frame with brass corners closing round the lectern leaf. On the swell f1755 the navy valance unrolls from its rod (f1755-1782), blank, its letters only faintly underdrawn, fringe and tassels dropping and swinging.",
 camera="The crane completes with ease-out onto the menu camera: vertical fov 30 deg, pitch 66.09 deg, distance 20.9.",
 technique="EV-DM E4 hero (2560x1440, 16 TAA, on ones; 39 renders) + COMP chrome: every chrome element is matted from the native 2560x1440 menu capture and placed as a flat at true depth near the final camera, moved only by homographies from the exported Blender camera track, so it is exact at the final pose (no 2D slides). Valance unroll = analytic roll with cylinder shading + fringe/tassel pendulums (period ~1.1 s). From f1756 the board albedo blends into a projection of the 2x UI-free menu plate, masked where pieces still settle.",
 material_behavior="The heraldic register now dominates (raised satin, gold, game-saturated colour) against the board's matte fields; walnut, velvet and brass exactly as the game art.",
 transition_out="Continuous.",
 emotional_purpose="Triumph: the world made whole, and set on the reader's table.",
 est_render_cost="Eevee E4 39 hero renders @1440p (~95 s) = ~62 min; COMP 39 x ~2 s.",
 eevee=dict(block="E4", r1080=0, r1440=39)),

dict(id="S25", name="What will the chronicles say of you?", act="V Question", start=1783, end=1854,
 anchor="'chronicles' f1801; 'say' f1824; 'you?' f1846; recession f1783-1824",
 summary="Near-stillness: the gold thread couches 'Chronica' on 'chronicles'; the leaf settles; the page stays blank",
 audio_event="'what' f1783, 'will' f1792, 'the' f1797, 'chronicles' f1801 (stressed, to f1821), 'say' f1824, 'of' f1838, 'you?' f1846 (to f1855). The music recedes ~19 dB (f1783 -> f1824); bass gone by f1823; a faint high chord remains.",
 visual_action="Motion stops except thread and light. The board's convergence finishes invisibly (Eevee -> the real game board, f1772-1798, before the title begins; in-world nameplates and unit shields from the native capture settle in inside the same dissolve). On 'chronicles' (f1787-1822) the gold thread climbs into the valance and couches C-h-r-o-n-i-c-a letter by letter, ~4 frames per letter, a small needle glint (L2) leading each stroke; then the crown, fleurs-de-lis and diamonds (f1824-1846); the last stitch pulls tight on 'you?' f1846. The leaf makes its last settle into the frame's lip (f1838-1850, <= 2 px, shadow tightening) and its drypoint ruling catches the light once on 'you?'. Banner and fringe sway decays below 1 px.",
 camera="Locked on the menu camera.",
 technique="COMP at the exact menu_layout px_2560x1440 rects: native-capture board (card interior inpainted) under the chrome layers; title stitch-on revealed from the logo_title gold mask along its skeleton in needle-path order with a travelling needle glint; E4 renders f1783-1798 (16) complete the dissolve; leaf/frame settle as a 2D layer with its shadow.",
 material_behavior="Gold floss on navy damask, twisted cord and fringe exactly as logo_title; the parchment interior blank; navy velvet stays matte.",
 transition_out="Hold into S26.",
 emotional_purpose="The question is turned to the player, and the title answers 'chronicles'.",
 est_render_cost="Eevee E4 16 hero renders + 1 registration still (32 TAA) = ~27 min; COMP 72 x ~3 s = ~4 CPU-min.",
 eevee=dict(block="E4", r1080=0, r1440=17)),

dict(id="S26", name="The page waits (hand-off)", act="V Question", start=1855, end=1983,
 anchor="ring-out f1855-1983; micro-fade f1982",
 summary="Near-still menu; metal flare 3 of 3 along the title; locked and identical from f1929; overlay dissolve to the live menu",
 audio_event="Narration ends f1855. 4.27 s ring-out of a soft, unresolved high chord (Am7/C6 colour), -44 -> -48 dBFS, no fade to silence; micro-fade f1982.",
 visual_action="The menu composition, near-still: the game board, walnut bar, gold-stitched 'Chronica' valance, lion banners, both candles, carved lions and the blank parchment card. METAL FLARE 3 of 3 (f1862-1904): one slow gold sheen sweeps left to right along 'Chronica' (metal reaching #FFF3D6 for 2 frames near f1883), then rests. Candle flames flicker sprite-locally (2-3 %) and settle to exactly the sprite art by f1928. From f1929 every animated layer is zero: f1929-1983 are identical (55 frames), the live menu's first frame with the card left blank. The overlay holds f1983 while the engine boots (gold progress thread at the bottom), then dissolves (0.9 s) to the live menu, whose title and buttons write themselves onto the blank page.",
 camera="Locked (menu camera).",
 technique="COMP only: base = native 2560x1440 capture of the menu's first frame with the card's text and buttons removed and the parchment re-synthesised from the 9-slice; sheen = R25 relight of the logo layer with the metal environment term; flame warp layer; a 4:3 variant composited at base_4x3 rects; acceptance test against the live capture.",
 material_behavior="Static, exact game art; only the flame and metal-sheen layers animate, then stop.",
 transition_out="Overlay hold, then the 0.9 s CSS dissolve to the live main menu (intro_overlay_snippet.html).",
 emotional_purpose="Calm resolve: the chronicle waits for the player's hand.",
 est_render_cost="COMP 129 x ~0.5 s = ~1 CPU-min.",
 eevee=dict(block="", r1080=0, r1440=0)),
]
